### PR TITLE
minor update for newer dependencies [dependency-update]

### PR DESCRIPTION
**Pull request by barker29**
This has been tested with MFEM 3.4 and hypre 2.15.1

TODO:

- [x] fix `.travis.yml`

### CODE REVIEW

**Comment by barker29** [comment]
Definitely need to fix `travis.yml` for the new dependencies.

**Comment by chakshinglee** [comment]
Do you plan to fix `travis.yml` in this PR or elsewhere?

**Comment by barker29** [comment]
I plan to fix it here, but I need to figure out how Travis handles the "cached" libraries (will need to update them).

**Review by chakshinglee — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
