### PR TITLE
Add W block support

### PR DESCRIPTION
**Pull request by gelever**
The much anticipated w_block branch:
- Support for W block in mixed system
- Minor changes throughout to improve readability

- [x] Fix copyright

### CODE REVIEW

**Review by barker29 — APPROVED** [review]
Looks good, detailed comments on institutional bitbucket.

**Comment by chakshinglee** [comment]
It remains to update the header?

**Comment by gelever** [comment]
@chakshinglee I think got them all with aba2f1b, if I missed anything let me know

**Comment by gelever** [comment]
What should be done w/ the CI stuff?

nvm, I see ` feature/travis-ci `

**Review by chakshinglee — APPROVED** [review]

**Comment by barker29** [comment]
Please ignore the Travis stuff and merge this if you think it's ready. (If you want to take a hand at fixing the `.travis.yml` file please do, I can't figure it out).

**Comment by gelever** [comment]
@barker29 ok, I'll check it out.  How do you test it?  Just upload it to GitHub and hope it works?

**Pull request merged**
